//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticlesCategories = new HashSet<ArticlesCategory>();
            this.ArticlesTags = new HashSet<ArticlesTag>();
            this.Comments = new HashSet<Comment>();
            this.DownloadableResources = new HashSet<DownloadableResource>();
            this.Exhibits = new HashSet<Exhibit>();
            this.Galleries = new HashSet<Gallery>();
            this.JournalArticles = new HashSet<JournalArticle>();
            this.Podcasts = new HashSet<Podcast>();
        }
    
        public int id { get; set; }
        public string title_en { get; set; }
        public string title_az { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string content_en { get; set; }
        public string content_az { get; set; }
        public int title_img_id { get; set; }
        public int author_id { get; set; }
        public int editor_id { get; set; }
        public int views_count { get; set; }
        public byte published { get; set; }
    
        public virtual User Author { get; set; }
        public virtual User Editor { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlesCategory> ArticlesCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlesTag> ArticlesTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DownloadableResource> DownloadableResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exhibit> Exhibits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gallery> Galleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalArticle> JournalArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podcast> Podcasts { get; set; }
    }
}
