//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadableResource
    {
        public int id { get; set; }
        public int article_id { get; set; }
        public string title { get; set; }
        public string lang { get; set; }
        public string file_dir { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
