//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExhibitData
    {
        public int id { get; set; }
        public Nullable<int> exhibit_column_id { get; set; }
        public string content_en { get; set; }
        public string content_az { get; set; }
    
        public virtual ExhibitColumn ExhibitColumn { get; set; }
    }
}
