//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesMeta
    {
        public int id { get; set; }
        public int image_id { get; set; }
        public string meta_name { get; set; }
        public string meta_value { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
