//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User Author { get; set; }
        public virtual User User { get; set; }
    }
}
