//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Articles = new HashSet<Article>();
            this.ArticlesEdited = new HashSet<Article>();
            this.Comments = new HashSet<Comment>();
            this.SubscriptionsToAuthors = new HashSet<Subscription>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<byte> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string about { get; set; }
        public string biography { get; set; }
        public string phone { get; set; }
        public int user_group_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> education_lvl_id { get; set; }
        public Nullable<int> university_id { get; set; }
        public string major { get; set; }
        public string employer { get; set; }
        public string job_title { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public string token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> ArticlesEdited { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Country Country { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> SubscriptionsToAuthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual University University { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
